## Download the zip file and open in working directory.
## Now we load the data into dataframes.
data <- cbind(read_lines("UCI HAR Dataset/train/subject_train.txt"),
              read_lines("UCI HAR Dataset/train/X_train.txt"),
              read_lines("UCI HAR Dataset/train/Y_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt"),
              read_lines("UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt"),
              read_lines("UCI HAR Dataset/test/subject_test.txt"),
              read_lines("UCI HAR Dataset/test/X_test.txt"),
              read_lines("UCI HAR Dataset/test/Y_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt"),
              read_lines("UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt"),
              )
